### ISSUE TITLE
image is not shown

### ISSUE THREAD

**Issue by ol-nikitagr** [tejasvi/markless#5]
```
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
```
➜  ~ code --version            
1.57.0
b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
x64
```
![image](https://user-images.githubusercontent.com/60471227/122401460-4af37000-cf85-11eb-9ead-5ff257beb4a1.png)

**Comment by Sean10** [comment]
Whether your picture's path is relative to your markdown file ?

And whether your picture's path is relative to your vscode opened  directory.

If you just open the directory which directly contains your markdown file , i think the picture preview will work.

**Comment by ol-nikitagr** [comment]
If I use Markdown: Markdown Preview Enchanced: Open Preview To The Side it renders just fine:
![image](https://user-images.githubusercontent.com/60471227/122403250-e6391500-cf86-11eb-8d76-66659c6339b3.png)

Picture path is relative both: to vscode project's directory and to markdown path mentioned file as well.

Also, disabling other extensions doesn't solve the problem, which leads to **problem is within `markless` extension.**

**Comment by Sean10** [comment]
You could just click the `inlinePreview` picture. It will show the file relative to your vscode project's directory. If it doesn't exist, it means your relative path is not correctly for the project root folder. 

And Markdown Preview extension supports render the picture whose path is relative to the markdown file. So they are different in the preview appearance.

**Comment by ol-nikitagr** [comment]
ohh yeah for some reason path is `home/${USER}/attachments/****.png` which is wrong.
It should be `home/${USER}/notes/attachments/****.png`

**Comment by ol-nikitagr** [comment]
It worked when I deleted **../**

>And Markdown Preview extension supports render the picture whose path is relative to the markdown file. So they are different in the preview appearance.

yeah don't you want to fix that?

**Comment by Sean10** [comment]
I'll try to support this.

**Comment by ol-nikitagr** [comment]
Thank you!~~~

**Comment by Sean10** [comment]
Before tejasvi publish the official, you could use this offline version package.
https://github.com/Sean10/markless/releases/tag/v1.0.8

**Comment by ol-nikitagr** [comment]
> Before tejasvi publish the official, you could use this offline version package.
> https://github.com/Sean10/markless/releases/tag/v1.0.8

thanks^^

**Comment by Sean10** [comment]
Since 1.58.2, vscode's comment preview can not work. [Comment reactions can't load images · Issue \#128770 · microsoft/vscode](https://github.com/microsoft/vscode/issues/128770).
